[package]
name = "rshell"
version = "0.1.0"
authors = ["Francisco Fernandez Castano <francisco.fernandez.castano@gmail.com>"]

[dependencies]
nix = "0.11.0"
rustyline = "1.0.0"
failure = "0.1.1"
nom = "^4.0"